# Site settings
title: VietStartup London
email:
description: VietStartup London landing page

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://VietStartupLondon.github.io" # the base hostname & protocol for your site

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: facebook
    url: https://facebook.com/vietstartup.london

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
